workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60

    environment:
      node: latest
      java: 21

    scripts:

      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Check dist folder
        script: |
          ls -la
          ls -la dist

      - name: Sync Capacitor
        script: |
          npx cap copy android
          npx cap sync android

      - name: Check Android assets
        script: |
          ls -la android/app/src/main
          ls -la android/app/src/main/assets || true

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
